### ISSUE TITLE
`mpr.Map` mysteriously unable to make maps? Webmapper too..?

### ISSUE THREAD

**Issue by DocSunset** [libmapper/libmapper#69]
I am working on a simple tool to make a slider for every destination signal that doesn't have an incoming map. Currently, tool listens for new signals. When it learns about a new destination signal, it creates a source signal of its own that duplicates the properties of the remote signal, then creates a map from the local source to the remote destination. A slider is created to allow the remote signal to be controlled.

Unfortunately, I am finding that my tool is unable to actually create the maps. Code to reproduce the issue follows:

This python script is just a dummy device with a destination signal:

```py
import signal
import libmapper as mpr

dev = None

def main():
  global dev
  dev = mpr.Device("device")

  def callback(sig, val):
    print(sig)
    print(val)

  in1 = dev.add_signal(dir=mpr.Direction.INCOMING
      , name="in1"
      , length=1
      , datatype=mpr.Type.FLOAT
      , callback=lambda s, e, i, v, t: callback(in1, v)
      )

  while True:
    dev.poll(1)

if __name__ == "__main__":
  signal.signal(signal.SIGTERM, lambda *args: dev.free())
  try:
    main()
  except KeyboardInterrupt:
    dev.free()
```

And this is a pared down version of my slider tool that illustrates the issue:

```py
from signal import SIGTERM, signal
import libmapper as mpr

class DestinationController():
  def __init__(self):
    self.dev = mpr.Device("DestinationController")
    while not self.dev.get_is_ready(): self.dev.poll(0)
    print("Device ready")
    self.dev.graph().add_callback(types=mpr.Type.SIGNAL
        , func=lambda t, sig, evt: self.graph_signal_callback(sig, evt)
        )
    self.dev.graph().subscribe(None, mpr.Type.OBJECT, -1)

  def loop(self):
      self.dev.poll(100)
      for sig in self.dev.signals():
        sig.set_value(1)

  def graph_signal_callback(self, sig, evt):
    if evt == mpr.Graph.Event.NEW:
      self.copy_signal(sig)

  def copy_signal(self, sig):
    if sig['direction'] == mpr.Direction.OUTGOING: return

    name = sig['device']['name'] + "/" + sig['name']
    minimum = sig['min']
    maximum = sig['max']
    copy = self.dev.add_signal(name = name
        , dir = mpr.Direction.OUTGOING
        , length = sig['length']
        , datatype = sig['type']
        , min = minimum if minimum is not None else 0
        , max = maximum if maximum is not None else 1
        )

    print("Connecting to {}".format(name))
    mpr.Map(copy, sig)

if __name__ == "__main__":
  print("Launching example")
  app = DestinationController()
  signal(SIGTERM, lambda *args: app.dev.free())
  print("Starting loop")
  try:
    while True:
      app.loop()
  except KeyboardInterrupt:
    app.dev.free()
    exit()
```

Scenario 1: Dummy before Controller
- start webmapper
- start the dummy device and wait for it to appear in webmapper
- start the controller device
- the controller reports that it is trying to connect, but no map appears in webmapper
- furthermore, if I try to make the map using webmapper it also fails
- if I keep trying, after about 30 seconds the map will work in webmapper

Scenario 2: Controller before dummy
- same as before, but start the controller first, then the dummy
- as before, the connection fails, and manually trying to make the map also fails

**Comment by DocSunset** [comment]
In the controller device, adding a graph callback for map events shows the following:

If I start the two example scripts as above, and do nothing in Webmapper, then after a moment the graph of the controller device reports a map removal. It seems like after this map removal event, I can make the map manually in Webmapper.

So I hypothesize that the controller device is creating the map locally, and the presence of this local map is what prevents Webmapper from manually making the map. If this is the case, I would expect that by commenting out the line `mpr.Map(copy, sig)` in the controller device, I should be able to make the map manually in Webmapper immediately as soon as the scripts are both started. I observe that I am unable to do so. Rather, if I try to make the map manually nothing happens, until some time later I see a map removal event reported by the controller device, after which point I can make the map no problem.

So from this I conclude that both my controller app and webmapper are unable to make a map to the dummy device; they attempt to do so, creating a local map which is later automatically removed by the library, after which point they can make a map.

I hypothesize that there is something wrong with my dummy app. However, I observe that if I start another simple dummy app as shown below, that I can make a map from it to the dummy receiver no problem, suggesting that it has something to do with my controller device.

```py
# dummy sender
import signal
import libmapper as mpr

dev = None

def main():
  global dev
  dev = mpr.Device("device")

  out1 = dev.add_signal(dir=mpr.Direction.OUTGOING
      , name="out1"
      , length=1
      , datatype=mpr.Type.FLOAT
      )

  while True:
    dev.poll(1)
    out1.set_value(1)

if __name__ == "__main__":
  signal.signal(signal.SIGTERM, lambda *args: dev.free())
  try:
    main()
  except KeyboardInterrupt:
    dev.free()
```

I hypothesize that maybe it has something to do with the fact that the controller device's signal is named similarly to the dummy device's signal. If this is the root of the issue, I would expect that I should be able to make the map if the controller device invents an unrelated name for its signals. Changing the line `name = ...` in the controller device to `name = "foobar"` does not produce a different behavior.

Giving up on this for now. Let me know if you figure it out in the meantime.

**Comment by malloch** [comment]
Hi @DocSunset thanks for the bug report! I can reproduce the buggy behaviour, which seems to be related to setting the device graph to subscribe to device metadata before creating a map causing pre-existing device metadata to interfere with the network link handshaking . I will investigate further and fix, but in the meantime you can workaround by changing line 12 of your "pared down slider" to:

`self.dev.graph().subscribe(None, mpr.Type.SIGNAL, -1)`

**Comment by malloch** [comment]
Should be fixed now in main branch: commit 48e4a6a

**Comment by DocSunset** [comment]
Thanks @malloch. My issue seems to be only partially fixed. I see the following behavior now after recompiling:

- start webmapper
- start the dummy device
- start the controller device ("pared down slider")
- the controller device tries to make a map (it prints "Connecting to device.1/in1"). No map appears in webmapper.
- after a moment, when the library for the controller device updates the sync record for the dummy device (`-- <graph> updating sync record for device 'device.1'`), the controller device receives a map removed event (`<libmapper.mapper.Map object at 0x7f1781f05c30> Event.REMOVED`).
- if at any point after starting the controller device I try to make the map manually in libmapper, it now succeeds.

So the issue is partially fixed. I can now make the map manually in webmapper as expected. However, the call to `mpr.Map` in the controller device script still fails mysteriously.

Here is the code I'm using for the controller device just to make sure we're still on the same page. The dummy device probably doesn't matter?

```py
from signal import SIGTERM, signal
import libmapper as mpr

class DestinationController():
  def __init__(self):
    self.dev = mpr.Device("DestinationController")
    while not self.dev.get_is_ready(): self.dev.poll(0)
    print("Device ready")
    self.dev.graph().add_callback(types=mpr.Type.SIGNAL
        , func=lambda t, sig, evt: self.graph_signal_callback(sig, evt)
        )
    self.dev.graph().add_callback(types=mpr.Type.MAP
        , func=lambda t, map, evt: self.graph_map_callback(map, evt)
        )
    self.dev.graph().subscribe(None, mpr.Type.OBJECT, -1) # behavior is roughly the same if I change this to mpr.Type.SIGNAL; the map removed event comes before the sync record update

  def loop(self):
      self.dev.poll(100)
      for sig in self.dev.signals():
        sig.set_value(1)

  def graph_signal_callback(self, sig, evt):
    if evt == mpr.Graph.Event.NEW:
      self.copy_signal(sig)

  def graph_map_callback(self, map, evt):
    print(map, evt)

  def copy_signal(self, sig):
    if sig['direction'] == mpr.Direction.OUTGOING: return

    name = sig['device']['name'] + "/" + sig['name']
    minimum = sig['min']
    maximum = sig['max']
    copy = self.dev.add_signal(name = name
        , dir = mpr.Direction.OUTGOING
        , length = sig['length']
        , datatype = sig['type']
        , min = minimum if minimum is not None else 0
        , max = maximum if maximum is not None else 1
        )
    copy['local_copy'] = 1

    print("Connecting to {}".format(name))
    m = mpr.Map(copy, sig)

if __name__ == "__main__":
  print("Launching example")
  app = DestinationController()
  signal(SIGTERM, lambda *args: app.dev.free())
  print("Starting loop")
  try:
    while True:
      app.loop()
  except KeyboardInterrupt:
    app.dev.free()
    exit()
```

**Comment by malloch** [comment]
Hi @DocSunset the problem with the example code is that `push()` is not called on the new map to sync it with the distributed graph. The local copy of the map (owned by your `self.dev.graph`) times out and is removed unless it receives notice that the map exists on the distributed graph.

This is an easy mistake to make! I think there is an argument here for at least improving the documentation for the Python bindings, and possibly for modifying libmapper's behaviour. Obviously we want user code to be able to set properties of the map before sync, but perhaps staged properties could be synced on the next call to `poll()` even if `push()` is not called.

**Comment by malloch** [comment]
You just need to modify the line in the example code from `m = mpr.Map(copy, sig)` to `m = mpr.Map(copy, sig).push()`

**Comment by DocSunset** [comment]
Yep, that fixes it. I guess I was not expecting to have to do that, since there is no equivalent step when creating a device or a signal. I would advocate for the call to `push()` being optional. What are the circumstances in which 'mpr_map_new` is called? Other than making local records of remote maps, in which case the call to push is unnecessary since there are no staged changes, it seems like the only time you would call it is to make a new map, in which case the call to push is implied?

Thanks again for your help!

**Comment by malloch** [comment]
Devices and signals instantiated with a constructor are local resources so there is no need to call `push()`, but you do need to call `push()` after editing properties of remote devices and signals (e.g. adding metadata). Maps are _always remote_ resources since they "live" on the network. This is well documented in the C/C++ API documentation but the Python documentation may need some improvement!

**Comment by DocSunset** [comment]
Thanks, that clears it up. I'll have to review the docs a little more closely... Cheers.

**Comment by malloch** [comment]
Commit 121a098 adds the behaviour we discussed – during the 2-stage map cleanup process the graph will first try to push staged maps to the network. This means calling `push()` on a map is _recommended_ (to immediately start the map handshake protocol) but not _necessary_.
